# Model Paths
models:
  phi4:
    path: "../../phi-4-multi/models/microsoft--Phi-4-multimodal-instruct"
    device: "cuda"
    dtype: "float16"
    max_new_tokens: 512
    temperature: 0.9
    top_p: 0.9
  csm:
    path: "../csm-multi/models"
    device: "cuda"
    dtype: "bfloat16"
    max_seq_len: 4096

# Audio Settings
audio:
  sample_rate: 44100  # Updated to match hardware default
  channels: 1
  chunk_size: 1024
  format: "pyaudio.paInt16"  # Changed to more widely supported format
  max_recording_seconds: 60

# Pipeline Settings
pipeline:
  memory_limit_mb: 4096
  enable_cuda_optimization: true
  use_flash_attention: true
  streaming_enabled: true
  cuda_memory_fraction: 0.8

# Logging
logging:
  level: "INFO"
  file: "voice_assistant.log"
  console_output: true