servers:
  memory:
    enabled: true
    params:
      model: ollama/Llama3B-uncensored:latest
      memory_dir: ~/basic-memory
      verbose: false
      default_context_depth: 2
    type: memory
  web_search:
    enabled: false
    params: {}
    type: web_search
