models:

  XXS:
    name: qwen3:1B

  XS:
    name: qwen3:2B
  
  S:
    name: qwen3:4B

  M:
    name: qwen3:8B
  
  L:
    name: qwen3:14B
  
  LEXI:
    name: Lexi:latest

# --- Memory System Configuration ---
memory:
  chromadb:
    path: "memories/chroma_db"  # Path to store ChromaDB persistent data
    collection_name: "bella_memories"
    # Using cosine distance for embeddings is standard practice
    metadata: {"hnsw:space": "cosine"}