models:

  gemma3:
    name: "Gemma3:latest"
    description: "Google Gemma with vision capabilities"
    parameters:
      temperature: 0.6
      top_p: 0.9
      max_tokens: 100
      repetition_penalty: 1.05

#MODELS TO TEST:

  Nemo:
    name: "Nemo:latest"
    description: "Uncensored model, rp fine tuned, with tool use"
    parameters:
      temperature: 0.7
      top_p: 0.95
      top_k: 40
      repeat_penalty: 1.05
      min_p: 0.05
      max_tokens: 100
      repetition_penalty: 1.05

  Lexi:
    name: "Lexi:latest"
    description: "Uncensored model, with tool use"
    parameters:
      temperature: 0.8
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.15
      max_tokens: 100
      min_p: 0.05

default_model: "Lexi"  # Default model to use