models:

  Gemma:
    name: "gemma3-tools:latest"
    description: "Google Gemma with vision capabilities and tool use"
    parameters:
      top_p: 0.9
      max_tokens: 100
      repetition_penalty: 1.05

#MODELS TO TEST:

  Mistral:
    name: "Mistral-24B:latest"
    description: "Large model with tool use"
    parameters:
      top_p: 0.95
      top_k: 40
      repeat_penalty: 1.05
      min_p: 0.05
      max_tokens: 100
      repetition_penalty: 1.05

  Lexi:
    name: "Lexi:latest"
    description: "Uncensored model, with tool use"
    parameters:
      temperature: 0.8
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.15
      max_tokens: 100
      min_p: 0.05

default_model: "Mistral"  # Default model to use

# --- Memory System Configuration ---
memory:
  chromadb:
    path: "memories/chroma_db"  # Path to store ChromaDB persistent data
    collection_name: "bella_memories"
    # Using cosine distance for embeddings is standard practice
    metadata: {"hnsw:space": "cosine"}