name: sesame-env
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - cuda-toolkit
  - torchaudio
  - torchvision
  - transformers=4.49.0
  - pip
  - pip:
    - flash-attn==2.7.4.post1
    - accelerate==1.3.0
    - peft==0.13.2
    - soundfile==0.13.1
    - pillow==11.1.0
    - scipy==1.15.2
    - backoff==2.2.1
    - tokenizers==0.21.0
    - huggingface-hub==0.28.1
    - moshi==0.2.2
    - torchtune==0.4.0
    - torchao==0.9.0