models:

  gemma3:
    name: "Gemma3:latest"
    description: "Google Gemma with vision capabilities"
    parameters:
      temperature: 0.6
      top_p: 0.9
      max_tokens: 60
      repetition_penalty: 1.05

default_model: "gemma3"  # Default model to use